// ==============================================================================
// HealthGrid Clinician Portal — Authentic Clinical Mock Data Seed
// Matches Reference Design: "My queue Reference.png"
// ==============================================================================

import type {
  ClinicianProfile,
  FacilityEntity,
  PatientEntity,
  PatientQueueItem,
  ResultItem,
  FollowUpItem,
  ReferralItem,
  ClinicalInboxItem,
  OrderSetTemplate,
  ClinicalEncounter,
} from '../../types/clinician';

export const SEED_CLINICIAN: ClinicianProfile = {
  id: 'dr_mohamed_001',
  name: 'Dr. Mohamed',
  title: 'Consultant Physician',
  specialty: 'General Medicine',
  qualification: 'MBBS, MD (Gen Med), MRCP',
  regNumber: 'TMC-84920-IND',
  facilityId: 'fac_apollo_chennai',
  facilityName: 'Apollo Clinic, Chennai',
  avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
  phone: '+91 98401 22891',
  email: 'dr.mohamed@healthgrid.med',
};

export const SEED_FACILITIES: FacilityEntity[] = [
  {
    id: 'fac_apollo_chennai',
    name: 'Apollo Clinic, Chennai',
    city: 'Chennai',
    address: 'Greams Road, Thousand Lights, Chennai, TN 600006',
    isPrimary: true,
  },
  {
    id: 'fac_gmch_vellore',
    name: 'Govt. Medical College Hospital (GMCH)',
    city: 'Vellore',
    address: 'Adukkamparai, Vellore, TN 632011',
  },
  {
    id: 'fac_sims_vadapalani',
    name: 'SIMS Super Specialty Hospital',
    city: 'Chennai',
    address: 'Jawaharlal Nehru Salai, Vadapalani, Chennai, TN 600026',
  },
];

// Seed Patients
export const SEED_PATIENTS: PatientEntity[] = [
  {
    id: 'pat_priya_sharma',
    uhid: 'AP001982',
    abhaId: '****4921',
    name: 'Priya Sharma',
    age: 28,
    gender: 'Female',
    bloodGroup: 'B+',
    phone: '+91 94451 98210',
    email: 'priya.sharma@example.com',
    address: 'Flat 4B, Emerald Heights, Anna Nagar, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Fever and body ache for 2 days',
    vitals: {
      tempF: 99.1,
      pulseBpm: 98,
      bpSystolic: 118,
      bpDiastolic: 76,
      spo2Percent: 98,
      respRate: 18,
      weightKg: 58,
      heightCm: 162,
      bmi: 22.1,
      recordedAt: '09:18 AM',
    },
    allergies: [],
    medications: [],
    problems: [
      {
        id: 'prob_101',
        code: 'A90',
        name: 'History of Dengue Fever',
        category: 'Infectious Disease',
        onsetDate: '2024-08-14',
        status: 'RESOLVED',
        notes: 'Managed conservatively. Platelets nadir was 85,000.',
      },
    ],
    investigations: [
      {
        id: 'inv_101',
        testName: 'Complete Blood Count (CBC)',
        date: '24 Sep 2025',
        status: 'Normal',
        summary: 'Hb: 12.8 g/dL, TLC: 7,400 /uL, Platelets: 240,000 /uL',
      },
    ],
    pastVisits: [
      {
        id: 'vis_101',
        date: '18 Jun 2025',
        reason: 'Viral fever & malaise',
        provider: 'Dr. Mohamed',
        facility: 'Apollo Clinic, Chennai',
        summary: 'Symptomatic Paracetamol + hydration therapy. Resolved in 4 days.',
      },
    ],
    careGaps: [
      {
        id: 'gap_101',
        title: 'Annual Cervical Cancer Screening',
        dueText: 'Due in 2 months',
        status: 'DUE_SOON',
      },
    ],
    careTeam: [
      { role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' },
    ],
  },
  {
    id: 'pat_arun_prakash',
    uhid: 'AP002341',
    abhaId: '****7109',
    name: 'Arun Prakash',
    age: 42,
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '+91 98842 10928',
    email: 'arun.prakash@example.com',
    address: 'Plot 12, T. Nagar, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Hypertension follow-up',
    vitals: {
      tempF: 98.6,
      pulseBpm: 74,
      bpSystolic: 138,
      bpDiastolic: 88,
      spo2Percent: 99,
      respRate: 16,
      weightKg: 76,
      heightCm: 174,
      bmi: 25.1,
      recordedAt: '09:45 AM',
    },
    allergies: [
      {
        id: 'alg_201',
        allergen: 'Penicillin',
        category: 'MEDICATION',
        severity: 'SEVERE',
        reaction: 'Urticarial rash & facial angioedema',
        verifiedDate: '2021-03-10',
        status: 'ACTIVE',
      },
    ],
    medications: [
      {
        id: 'med_201',
        name: 'Amlodipine',
        genericName: 'Amlodipine Besylate',
        dosage: '5 mg',
        route: 'Oral',
        frequency: 'Once Daily (OD)',
        startDate: '2023-01-15',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take in the morning with water',
        isJanAushadhiAvailable: true,
        genericSavingsPercent: 78,
      },
      {
        id: 'med_202',
        name: 'Telmisartan',
        genericName: 'Telmisartan',
        dosage: '40 mg',
        route: 'Oral',
        frequency: 'Once Daily (OD)',
        startDate: '2023-06-20',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take post breakfast',
        isJanAushadhiAvailable: true,
        genericSavingsPercent: 82,
      },
    ],
    problems: [
      {
        id: 'prob_201',
        code: 'I10',
        name: 'Essential Hypertension',
        category: 'Cardiovascular',
        onsetDate: '2022-11-10',
        status: 'CHRONIC',
        notes: 'Target BP < 130/80 mmHg. Good adherence.',
      },
    ],
    investigations: [
      {
        id: 'inv_201',
        testName: 'Chest X-Ray PA View',
        date: '29 Sep 2025',
        status: 'Normal',
        summary: 'No cardiomegaly. Lung fields clear.',
      },
    ],
    pastVisits: [
      {
        id: 'vis_201',
        date: '15 Jul 2025',
        reason: 'Quarterly Hypertension Review',
        provider: 'Dr. Mohamed',
        facility: 'Apollo Clinic, Chennai',
        summary: 'BP 134/86 mmHg. Maintained on Amlodipine + Telmisartan.',
      },
    ],
    careGaps: [
      {
        id: 'gap_201',
        title: 'Annual Serum Creatinine & eGFR',
        dueText: 'Due this month',
        status: 'DUE_SOON',
      },
    ],
    careTeam: [
      { role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' },
    ],
  },
  {
    id: 'pat_meena_iyer',
    uhid: 'AP001409',
    abhaId: '****3890',
    name: 'Meena Iyer',
    age: 56,
    gender: 'Female',
    bloodGroup: 'A+',
    phone: '+91 97890 38901',
    address: '45, R.A. Puram, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Lab report discussion — Critical High K+',
    vitals: {
      tempF: 98.4,
      pulseBpm: 84,
      bpSystolic: 142,
      bpDiastolic: 90,
      spo2Percent: 97,
      respRate: 18,
      weightKg: 64,
      heightCm: 158,
      bmi: 25.6,
      recordedAt: '10:15 AM',
    },
    allergies: [
      {
        id: 'alg_301',
        allergen: 'Sulfa Drugs',
        category: 'MEDICATION',
        severity: 'MODERATE',
        reaction: 'Maculopapular rash',
        verifiedDate: '2019-05-18',
        status: 'ACTIVE',
      },
    ],
    medications: [
      {
        id: 'med_301',
        name: 'Spironolactone',
        genericName: 'Spironolactone',
        dosage: '25 mg',
        route: 'Oral',
        frequency: 'Once Daily (OD)',
        startDate: '2024-02-10',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take in the morning',
      },
      {
        id: 'med_302',
        name: 'Enalapril',
        genericName: 'Enalapril Maleate',
        dosage: '10 mg',
        route: 'Oral',
        frequency: 'Twice Daily (BD)',
        startDate: '2023-09-01',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take post meals',
      },
    ],
    problems: [
      {
        id: 'prob_301',
        code: 'N18.3',
        name: 'Chronic Kidney Disease, Stage 3a',
        category: 'Renal',
        onsetDate: '2023-08-15',
        status: 'CHRONIC',
        notes: 'eGFR 52 mL/min. Prone to hyperkalemia with ACEi/MRA combo.',
      },
    ],
    investigations: [
      {
        id: 'inv_301',
        testName: 'Serum Electrolytes',
        date: 'Today',
        status: 'Critical',
        summary: 'Potassium: 6.2 mmol/L (Critical High), Sodium: 138 mmol/L',
      },
    ],
    pastVisits: [
      {
        id: 'vis_301',
        date: '20 Aug 2025',
        reason: 'CKD Routine Review',
        provider: 'Dr. Mohamed',
        facility: 'Apollo Clinic, Chennai',
        summary: 'Ordered repeat renal panel and advised low potassium diet.',
      },
    ],
    careGaps: [
      {
        id: 'gap_301',
        title: 'Repeat Serum Potassium & ECG',
        dueText: 'Immediate (Stat)',
        status: 'OVERDUE',
      },
    ],
    careTeam: [
      { role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' },
      { role: 'Consultant Nephrologist', name: 'Dr. K. Swaminathan', specialty: 'Nephrology' },
    ],
  },
  {
    id: 'pat_sathish_n',
    uhid: 'AP003112',
    abhaId: '****6234',
    name: 'Sathish N',
    age: 38,
    gender: 'Male',
    bloodGroup: 'B+',
    phone: '+91 99403 62340',
    address: '18, Velachery Main Rd, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Post hospitalization Breathlessness',
    vitals: {
      tempF: 98.8,
      pulseBpm: 102,
      bpSystolic: 124,
      bpDiastolic: 82,
      spo2Percent: 95,
      respRate: 22,
      weightKg: 71,
      heightCm: 170,
      bmi: 24.6,
      recordedAt: '10:50 AM',
    },
    allergies: [],
    medications: [
      {
        id: 'med_401',
        name: 'Inhaler Budecort',
        genericName: 'Budesonide Rotacaps',
        dosage: '200 mcg',
        route: 'Inhalation',
        frequency: 'Twice Daily (BD)',
        startDate: '2025-09-15',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Rinse mouth after inhalation',
      },
    ],
    problems: [
      {
        id: 'prob_401',
        code: 'J45.909',
        name: 'Bronchial Asthma with acute exacerbation',
        category: 'Respiratory',
        onsetDate: '2020-04-12',
        status: 'ACTIVE',
        notes: 'Discharged from ward 2 weeks ago post IV bronchodilator.',
      },
    ],
    investigations: [
      {
        id: 'inv_401',
        testName: 'Spirometry (PFT)',
        date: '16 Sep 2025',
        status: 'Abnormal',
        summary: 'FEV1/FVC: 68%, significant reversibility post-salbutamol.',
      },
    ],
    pastVisits: [
      {
        id: 'vis_401',
        date: '15 Sep 2025',
        reason: 'Hospital Discharge Follow-up',
        provider: 'Dr. Mohamed',
        facility: 'Apollo Clinic, Chennai',
        summary: 'Discharged on tapering oral steroids and ICS inhaler.',
      },
    ],
    careGaps: [],
    careTeam: [
      { role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' },
    ],
  },
  {
    id: 'pat_ramesh_kumar',
    uhid: 'AP001120',
    abhaId: '****8811',
    name: 'Ramesh Kumar',
    age: 50,
    gender: 'Male',
    bloodGroup: 'O+',
    phone: '+91 98410 88112',
    address: '8, Mylapore, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Type 2 Diabetes — HbA1c 8.1%',
    vitals: {
      tempF: 98.6,
      pulseBpm: 76,
      bpSystolic: 132,
      bpDiastolic: 84,
      spo2Percent: 99,
      respRate: 16,
      weightKg: 82,
      heightCm: 168,
      bmi: 29.0,
      recordedAt: '08:45 AM',
    },
    allergies: [],
    medications: [
      {
        id: 'med_501',
        name: 'Metformin',
        genericName: 'Metformin HCl',
        dosage: '500 mg',
        route: 'Oral',
        frequency: 'Twice Daily (BD)',
        startDate: '2022-04-01',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take with food to minimize GI distress',
        isJanAushadhiAvailable: true,
        genericSavingsPercent: 88,
      },
    ],
    problems: [
      {
        id: 'prob_501',
        code: 'E11.9',
        name: 'Type 2 Diabetes Mellitus',
        category: 'Endocrine',
        onsetDate: '2021-02-14',
        status: 'CHRONIC',
        notes: 'HbA1c suboptimal at 8.1%. Consider adding SGLT2i or DPP-4i.',
      },
    ],
    investigations: [
      {
        id: 'inv_501',
        testName: 'Glycated Hemoglobin (HbA1c)',
        date: '28 Sep 2025',
        status: 'Abnormal',
        summary: '8.1% (Target < 7.0%)',
      },
    ],
    pastVisits: [],
    careGaps: [
      {
        id: 'gap_501',
        title: 'Annual Diabetic Retinopathy Fundus Exam',
        dueText: 'Overdue by 1 month',
        status: 'OVERDUE',
      },
    ],
    careTeam: [
      { role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' },
    ],
  },
  {
    id: 'pat_lakshmi_devi',
    uhid: 'AP001887',
    abhaId: '****2901',
    name: 'Lakshmi Devi',
    age: 62,
    gender: 'Female',
    bloodGroup: 'B+',
    phone: '+91 94441 29010',
    address: '14, Adyar, Chennai',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    primaryProblem: 'Lipid Profile review & Knee Osteoarthritis',
    vitals: {
      tempF: 98.4,
      pulseBpm: 72,
      bpSystolic: 128,
      bpDiastolic: 80,
      spo2Percent: 98,
      recordedAt: '11:10 AM',
    },
    allergies: [],
    medications: [
      {
        id: 'med_601',
        name: 'Paracetamol',
        genericName: 'Paracetamol',
        dosage: '650 mg',
        route: 'Oral',
        frequency: 'SOS (As needed)',
        startDate: '2025-01-10',
        status: 'ACTIVE',
        prescriber: 'Dr. Mohamed',
        instructions: 'Take after food for joint ache',
      },
    ],
    problems: [
      {
        id: 'prob_601',
        code: 'M17.0',
        name: 'Bilateral Primary Osteoarthritis of Knee',
        category: 'Musculoskeletal',
        onsetDate: '2022-09-01',
        status: 'CHRONIC',
      },
    ],
    investigations: [
      {
        id: 'inv_601',
        testName: 'Lipid Profile',
        date: '27 Sep 2025',
        status: 'Normal',
        summary: 'Total Chol: 188 mg/dL, LDL: 104 mg/dL, HDL: 48 mg/dL',
      },
    ],
    pastVisits: [],
    careGaps: [],
    careTeam: [{ role: 'Primary Physician', name: 'Dr. Mohamed', specialty: 'General Medicine' }],
  },
];

// Seed Patient Queue Items matching reference image exactly
export const SEED_QUEUE_ITEMS: PatientQueueItem[] = [
  {
    id: 'q_001',
    patientId: 'pat_priya_sharma',
    patient: SEED_PATIENTS[0],
    appointmentId: 'apt_001',
    time: '09:30 AM',
    waitingMinutes: 12,
    status: 'WAITING',
    priority: 'ROUTINE',
    visitType: 'NEW_PATIENT',
    chiefComplaint: 'Fever, body ache for 2 days',
    roomNumber: 'Room 101',
  },
  {
    id: 'q_002',
    patientId: 'pat_arun_prakash',
    patient: SEED_PATIENTS[1],
    appointmentId: 'apt_002',
    time: '10:00 AM',
    waitingMinutes: 25,
    status: 'WAITING',
    priority: 'ROUTINE',
    visitType: 'FOLLOW_UP',
    chiefComplaint: 'Hypertension follow-up',
    roomNumber: 'Room 101',
  },
  {
    id: 'q_003',
    patientId: 'pat_meena_iyer',
    patient: SEED_PATIENTS[2],
    appointmentId: 'apt_003',
    time: '10:30 AM',
    waitingMinutes: 8,
    status: 'WAITING',
    priority: 'URGENT',
    visitType: 'RESULT_REVIEW',
    chiefComplaint: 'Lab report discussion',
    criticalAlert: 'High K+ (6.2)',
    roomNumber: 'Room 101',
  },
  {
    id: 'q_004',
    patientId: 'pat_sathish_n',
    patient: SEED_PATIENTS[3],
    appointmentId: 'apt_004',
    time: '11:00 AM',
    waitingMinutes: 5,
    status: 'WAITING',
    priority: 'ROUTINE',
    visitType: 'FOLLOW_UP',
    chiefComplaint: 'Post hospitalization / Breathlessness',
    roomNumber: 'Room 101',
  },
  {
    id: 'q_005',
    patientId: 'pat_ramesh_kumar',
    patient: SEED_PATIENTS[4],
    appointmentId: 'apt_005',
    time: '09:00 AM',
    waitingMinutes: 0,
    status: 'IN_CONSULTATION',
    priority: 'ROUTINE',
    visitType: 'FOLLOW_UP',
    chiefComplaint: 'Diabetic routine check & HbA1c review',
    roomNumber: 'Room 101',
  },
  {
    id: 'q_006',
    patientId: 'pat_lakshmi_devi',
    patient: SEED_PATIENTS[5],
    appointmentId: 'apt_006',
    time: '11:30 AM',
    waitingMinutes: 0,
    status: 'SCHEDULED',
    priority: 'ROUTINE',
    visitType: 'NEW_PATIENT',
    chiefComplaint: 'Knee joint pain & stiffness',
    roomNumber: 'Room 101',
  },
];

// Seed Recent Results to Review (Bottom Right card)
export const SEED_RESULTS: ResultItem[] = [
  {
    id: 'res_001',
    patientId: 'pat_meena_iyer',
    patientName: 'Meena Iyer',
    testName: 'Serum Potassium',
    category: 'Biochemistry',
    date: 'Today',
    status: 'NEW',
    isAbnormal: true,
    isCritical: true,
    value: '6.2',
    unit: 'mmol/L',
    referenceRange: '3.5 - 5.0 mmol/L',
    interpretation: 'CRITICAL HYPERKALEMIA: High risk of cardiac dysrhythmias. Immediate review of ACEi/Spironolactone required.',
  },
  {
    id: 'res_002',
    patientId: 'pat_arun_prakash',
    patientName: 'Arun Prakash',
    testName: 'Chest X-ray',
    category: 'Radiology',
    date: 'Today',
    status: 'NEW',
    isAbnormal: false,
    isCritical: false,
    value: 'Clear',
    interpretation: 'No active focal consolidation or acute cardiopulmonary abnormality detected.',
  },
  {
    id: 'res_003',
    patientId: 'pat_ramesh_kumar',
    patientName: 'Ramesh Kumar',
    testName: 'HbA1c',
    category: 'Biochemistry',
    date: '1 day ago',
    status: 'NEEDS_REVIEW',
    isAbnormal: true,
    isCritical: false,
    value: '8.1',
    unit: '%',
    referenceRange: '< 5.7% Normal, < 7.0% Diabetic Target',
    interpretation: 'Suboptimal glycemic control. Escalation of antihyperglycemic regimen indicated.',
  },
  {
    id: 'res_004',
    patientId: 'pat_lakshmi_devi',
    patientName: 'Lakshmi Devi',
    testName: 'Lipid Profile',
    category: 'Biochemistry',
    date: '2 days ago',
    status: 'NEW',
    isAbnormal: false,
    isCritical: false,
    value: 'Within limits',
    interpretation: 'Total Cholesterol: 188 mg/dL, Triglycerides: 142 mg/dL. Desirable lipid profile.',
  },
];

// Seed Follow-ups Due (Bottom Center card)
export const SEED_FOLLOW_UPS: FollowUpItem[] = [
  {
    id: 'fol_001',
    patientId: 'pat_ramesh_kumar',
    patientName: 'Ramesh Kumar',
    reason: 'HbA1c Review & Treatment Adjustment',
    dueDate: '2025-09-29',
    dueLabel: 'Today',
    priority: 'HIGH',
    status: 'PENDING',
    notes: 'Discuss initiation of SGLT2 inhibitor (Dapagliflozin 10mg) and diet modifications.',
  },
  {
    id: 'fol_002',
    patientId: 'pat_lakshmi_devi',
    patientName: 'Lakshmi Devi',
    reason: 'Knee X-ray & Ortho Physio Follow-up',
    dueDate: '2025-10-01',
    dueLabel: '2 days',
    priority: 'NORMAL',
    status: 'SCHEDULED',
    notes: 'Evaluate response to quadriceps strengthening physiotherapy and topical NSAID gel.',
  },
  {
    id: 'fol_003',
    patientId: 'pat_vikram_s',
    patientName: 'Vikram S',
    reason: 'Post procedure review',
    dueDate: '2025-10-02',
    dueLabel: '3 days',
    priority: 'NORMAL',
    status: 'SCHEDULED',
    notes: 'Suture line inspection and wound healing check post minor sebaceous cyst excision.',
  },
];

// Seed Referrals
export const SEED_REFERRALS: ReferralItem[] = [
  {
    id: 'ref_001',
    patientId: 'pat_priya_sharma',
    patientName: 'Priya Sharma',
    referringDoctor: 'Dr. Mohamed',
    targetSpecialty: 'Hematology',
    targetDoctorName: 'Dr. Anita Desai',
    reason: 'Post-dengue immune thrombocytopenia surveillance',
    priority: 'ROUTINE',
    clinicalSummary: 'Patient had dengue in 2024. Routine CBC today normal (2.4L platelets). Referral update confirmed no residual coagulopathy.',
    status: 'REPORT_RECEIVED',
    requestedDate: '2025-09-20',
    reportNotes: 'Hematologist note received: Peripheral smear normal, no atypia. Safe for routine discharge.',
  },
  {
    id: 'ref_002',
    patientId: 'pat_meena_iyer',
    patientName: 'Meena Iyer',
    referringDoctor: 'Dr. Mohamed',
    targetSpecialty: 'Nephrology',
    targetDoctorName: 'Dr. K. Swaminathan',
    reason: 'CKD Stage 3a with acute hyperkalemia',
    priority: 'URGENT',
    clinicalSummary: 'Serum K+ 6.2 mmol/L. Requires nephrology consult for medication overhaul.',
    status: 'SENT',
    requestedDate: '2025-09-29',
  },
];

// Seed Clinical Inbox Items
export const SEED_INBOX_ITEMS: ClinicalInboxItem[] = [
  {
    id: 'inb_001',
    type: 'RESULTS',
    priority: 'CRITICAL',
    patientId: 'pat_meena_iyer',
    patientName: 'Meena Iyer',
    patientAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: 'CRITICAL RESULT: Serum Potassium 6.2 mmol/L',
    summary: 'Biochemistry lab flagged critical hyperkalemia. Immediate physician intervention needed.',
    timestamp: '15 mins ago',
    isRead: false,
    isActioned: false,
    relatedId: 'res_001',
  },
  {
    id: 'inb_002',
    type: 'NOTES',
    priority: 'HIGH',
    patientId: 'pat_arun_prakash',
    patientName: 'Arun Prakash',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Unsigned Consultation Note (Encounter #4102)',
    summary: 'Hypertension encounter from earlier today requires final clinical sign-off.',
    timestamp: '45 mins ago',
    isRead: false,
    isActioned: false,
  },
  {
    id: 'inb_003',
    type: 'REFERRALS',
    priority: 'NORMAL',
    patientId: 'pat_priya_sharma',
    patientName: 'Priya Sharma',
    patientAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    title: 'Specialist Report Received from Dr. Anita Desai',
    summary: 'Hematology consult report for post-dengue surveillance is ready for review.',
    timestamp: '2 hours ago',
    isRead: false,
    isActioned: false,
    relatedId: 'ref_001',
  },
  {
    id: 'inb_004',
    type: 'FOLLOW_UPS',
    priority: 'HIGH',
    patientId: 'pat_ramesh_kumar',
    patientName: 'Ramesh Kumar',
    patientAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    title: 'Follow-up Due Today: HbA1c Glycemic Review',
    summary: 'Patient scheduled for quarterly diabetic evaluation and pharmacological escalation.',
    timestamp: '3 hours ago',
    isRead: false,
    isActioned: false,
    relatedId: 'fol_001',
  },
  {
    id: 'inb_005',
    type: 'PRESCRIPTIONS',
    priority: 'NORMAL',
    patientId: 'pat_arun_prakash',
    patientName: 'Arun Prakash',
    patientAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'Refill Request: Telmisartan 40mg (30-day)',
    summary: 'Patient requested refill via HealthGrid Personal app. Compliance confirmed.',
    timestamp: '4 hours ago',
    isRead: true,
    isActioned: false,
  },
  {
    id: 'inb_006',
    type: 'MESSAGES',
    priority: 'NORMAL',
    patientId: 'pat_sathish_n',
    patientName: 'Sathish N',
    patientAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: 'Patient Message: Clarification on inhaler frequency',
    summary: 'Asking if Budecort can be taken 3 times a day during damp evening weather.',
    timestamp: '5 hours ago',
    isRead: true,
    isActioned: false,
  },
];

// Seed Order Sets
export const SEED_ORDER_SETS: OrderSetTemplate[] = [
  {
    id: 'os_diabetes_followup',
    name: 'Diabetes Mellitus Routine Follow-up',
    specialty: 'General Medicine / Endocrinology',
    description: 'Quarterly comprehensive diabetic surveillance panel and microvascular care gaps.',
    items: [
      { category: 'LABORATORY', name: 'Glycated Hemoglobin (HbA1c)', code: 'LAB-HBA1C' },
      { category: 'LABORATORY', name: 'Fasting Lipid Profile', code: 'LAB-LIPID' },
      { category: 'LABORATORY', name: 'Serum Creatinine & eGFR', code: 'LAB-CREAT' },
      { category: 'LABORATORY', name: 'Urine Albumin-to-Creatinine Ratio (ACR)', code: 'LAB-UACR' },
      { category: 'REFERRAL', name: 'Ophthalmology Dilated Fundus Exam', code: 'REF-OPHTH' },
    ],
  },
  {
    id: 'os_chest_pain_acute',
    name: 'Acute Chest Pain Protocol',
    specialty: 'Cardiology / Emergency',
    description: 'Rapid cardiac enzyme, imaging, and telemetry bundle for acute coronary syndrome evaluation.',
    items: [
      { category: 'PROCEDURE', name: '12-Lead Electrocardiogram (ECG)', code: 'PROC-ECG' },
      { category: 'LABORATORY', name: 'High-Sensitivity Troponin I (hs-cTnI)', code: 'LAB-TROP' },
      { category: 'IMAGING', name: 'Chest X-Ray PA View (Portable)', code: 'IMG-CXR' },
      { category: 'LABORATORY', name: 'Serum Electrolytes (Na, K, Cl)', code: 'LAB-LYTES' },
      { category: 'REFERRAL', name: 'Stat Cardiology Consult', code: 'REF-CARD' },
    ],
  },
  {
    id: 'os_febrile_illness',
    name: 'Acute Febrile Illness & Dengue Workup',
    specialty: 'General Medicine',
    description: 'Comprehensive febrile panel with complete hemogram and vector-borne screening.',
    items: [
      { category: 'LABORATORY', name: 'Complete Blood Count (CBC) with Platelets', code: 'LAB-CBC' },
      { category: 'LABORATORY', name: 'Dengue NS1 Antigen & IgM/IgG Antibody', code: 'LAB-DENGUE' },
      { category: 'LABORATORY', name: 'Peripheral Blood Smear for Malarial Parasite', code: 'LAB-MP' },
      { category: 'LABORATORY', name: 'Liver Function Tests (LFT)', code: 'LAB-LFT' },
      { category: 'LABORATORY', name: 'Complete Urinalysis', code: 'LAB-URINE' },
    ],
  },
];

// Seed Clinical Encounters
export const SEED_ENCOUNTERS: ClinicalEncounter[] = [
  {
    id: 'enc_001',
    patientId: 'pat_priya_sharma',
    patient: SEED_PATIENTS[0],
    appointmentId: 'apt_001',
    clinicianId: 'dr_mohamed_001',
    facilityId: 'fac_apollo_chennai',
    date: '2025-09-29',
    startTime: '09:30 AM',
    status: 'IN_PROGRESS',
    visitType: 'NEW_PATIENT',
    chiefComplaint: 'Fever and body ache for 2 days',
    hpi: '28-year-old female presents with acute onset of high-grade fever associated with severe myalgia, retro-orbital pain, and generalized malaise for 48 hours. Denies chronic cough, hemoptysis, or urinary dysuria. Past history significant for uncomplicated dengue in 2024.',
    ros: {
      Constitutional: 'Positive for fever and rigors. Negative for significant weight loss.',
      Respiratory: 'Negative for dyspnea, wheezing, or cough.',
      Cardiovascular: 'Negative for palpitations, chest tightness.',
      Gastrointestinal: 'Mild nausea, no vomiting or diarrhea.',
      Skin: 'No petechiae, ecchymoses, or active maculopapular rash.',
    },
    vitals: {
      tempF: 99.1,
      pulseBpm: 98,
      bpSystolic: 118,
      bpDiastolic: 76,
      spo2Percent: 98,
      respRate: 18,
      weightKg: 58,
      heightCm: 162,
      bmi: 22.1,
      recordedAt: '09:18 AM',
    },
    physicalExam: {
      general: 'Conscious, oriented, febrile to touch. No pallor, icterus, or peripheral lymphadenopathy.',
      respiratory: 'Bilateral vesicular breath sounds, clear lung fields, no added sounds.',
      cardiovascular: 'S1, S2 heard normally. Regular rhythm. No murmurs.',
      abdomen: 'Soft, non-tender, no hepatosplenomegaly or ascites.',
      skin: 'No tourniquet sign or hemorrhagic spots.',
    },
    assessment: 'Acute Febrile Illness — likely viral syndrome; rule out secondary dengue or tropical arbovirus given seasonal peak.',
    diagnoses: [
      {
        id: 'diag_001',
        code: 'R50.9',
        name: 'Fever, unspecified',
        category: 'Symptom',
        onsetDate: '2025-09-27',
        status: 'ACTIVE',
      },
    ],
    plan: '1. Hydration therapy with oral rehydration solution (2-3 L/day).\n2. Paracetamol 650mg for antipyretic relief.\n3. Complete Blood Count and Dengue NS1 screening.\n4. Avoid NSAIDs (Ibuprofen/Aspirin) due to platelet bleeding risk.',
    medicationReconciliations: [],
    orders: [
      {
        id: 'ord_101',
        encounterId: 'enc_001',
        patientId: 'pat_priya_sharma',
        category: 'LABORATORY',
        name: 'Complete Blood Count (CBC) with Platelets',
        code: 'LAB-CBC',
        priority: 'STAT',
        status: 'SUBMITTED',
        orderedAt: '09:35 AM',
      },
      {
        id: 'ord_102',
        encounterId: 'enc_001',
        patientId: 'pat_priya_sharma',
        category: 'LABORATORY',
        name: 'Dengue NS1 Antigen Rapid Card',
        code: 'LAB-DENGUE-NS1',
        priority: 'ROUTINE',
        status: 'DRAFT',
        orderedAt: '09:36 AM',
      },
    ],
    prescriptions: [
      {
        medicineName: 'Paracetamol',
        dosage: '650 mg',
        frequency: 'TDS (Three times a day)',
        duration: '5 days',
        instructions: 'Take post meals when temperature > 99.5°F',
        isGeneric: true,
        janAushadhiPrice: 12.5,
        brandedPrice: 42.0,
      },
      {
        medicineName: 'Oral Rehydration Salts (ORS)',
        dosage: '1 Sachet',
        frequency: 'Daily in 1 Liter water',
        duration: '3 days',
        instructions: 'Sip throughout the day for electrolyte replenishment',
        isGeneric: true,
        janAushadhiPrice: 8.0,
        brandedPrice: 28.0,
      },
    ],
    referrals: [],
    followUp: {
      id: 'fol_enc_001',
      encounterId: 'enc_001',
      patientId: 'pat_priya_sharma',
      patientName: 'Priya Sharma',
      reason: 'Review CBC platelet count & defervescence',
      dueDate: '2025-10-01',
      dueLabel: '2 days',
      priority: 'HIGH',
      status: 'PENDING',
      notes: 'Review platelet trend. Return immediately if persistent vomiting, abdominal pain, or bleeding gums occur.',
    },
    patientInstructions: '1. Drink ample fluids (coconut water, ORS, lemon water).\n2. Rest adequately.\n3. Take Paracetamol 650mg strictly as prescribed.\n4. RED FLAGS: Extreme dizziness, severe abdominal pain, persistent vomiting, or petechiae/bleeding — report to emergency immediately.',
    soapNote: {
      subjective: 'Patient reports 2-day history of acute fever, generalized body aches, and retro-orbital headache. No GI upset or respiratory distress.',
      objective: 'Temp 99.1°F, PR 98 bpm, BP 118/76 mmHg, SpO2 98%. Chest clear, abdomen soft, no tourniquet sign.',
      assessment: 'Acute viral syndrome / suspect arboviral fever.',
      plan: 'CBC + Dengue NS1 ordered. Paracetamol 650mg TDS prescribed with hydration. Follow-up in 48 hours.',
    },
  },
];
